### ISSUE TITLE
请问第六卷、第七卷有吗?

### ISSUE THREAD

**Issue by BiCan12** [OriginZero/TheGreatLeaderChairmanMAO#1]
非常感谢您的分享，请问第六卷、第七卷有吗?

**Comment by OriginZero** [comment]
https://www.marxists.org/chinese/pdf/chinese_marxists/mao/20201007f.pdf

https://www.marxists.org/chinese/pdf/chinese_marxists/mao/20201007g.pdf

内容未验证
